# Generated by Django 4.1 on 2022-08-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t0',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='t1',
            fields=[
            ],
            options={
                'verbose_name_plural': 't1-name',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.order',),
        ),
    ]
